name: Checks

on: [push, pull_request]

jobs:
  Unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get install -y zlib1g-dev qtbase5-dev qt5-qmake qt5-default valgrind
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake qt@5 md5sha1sum
          fi
      - name: Configure
        run: |
          cd Project/GNU/CLI
          autoreconf -if
          ./configure
      - name: Build
        run: |
          cd Project/GNU/CLI
          make
      - name: Clone testing files
        run: |
          cd Project/GNU/CLI
          make clone_testing_files
      - name: Check
        run: |
          cd Project/GNU/CLI
          make check
      - name: Configure GUI
        run: |
          cd Project/Qt
          export PATH=/usr/local/opt/qt5/bin:$PATH
          ./prepare INCLUDEPATH+=/usr/local/include CONFIG+=c++11 -after QMAKE_MACOSX_DEPLOYMENT_TARGET=10.9
      - name: Build GUI
        run: |
          cd Project/Qt
          export PATH=/usr/local/opt/qt5/bin:$PATH
          make
